[phases.setup]
nixPkgs = ["python311", "postgresql"]

[phases.install]
cmds = ["pip install -r TijuanaRoadSafety/requirements.txt"]

[phases.build]
cmds = [
    "cd TijuanaRoadSafety",
    "python manage.py collectstatic --noinput"
]

[start]
cmd = "cd TijuanaRoadSafety && gunicorn TijuanaRoadSafety.wsgi:application --bind 0.0.0.0:$PORT"
