[build]
builder = "dockerfile"

[deploy]
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

# CRITICAL: Persistent storage for uploaded images
[[deploy.volumes]]
mountPath = "/app/media"
name = "pothole-images-volume"
size = "10GB"  # Adjust size as needed
