# Generated by Django 5.1.7 on 2025-09-07 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapapp', '0002_potholereport_delete_usersubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='potholereport',
            name='approximate_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='potholereport',
            name='submission_count',
            field=models.IntegerField(default=1),
        ),
    ]
