# Generated by Django 5.1.7 on 2025-09-28 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapapp', '0004_enhance_mobile_whatsapp_support'),
    ]

    operations = [
        migrations.AddField(
            model_name='potholereport',
            name='latest_submission_date',
            field=models.DateTimeField(auto_now_add=True, help_text='Date of the most recent submission for this pothole', null=True),
        ),
    ]
